server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlite:./data/solicitudes.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  security:
    user:
      name: devuser
      password: devpass

logging:
  level:
    root: INFO